name: Java first workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v4

      - name: Get Jdk
        uses: actions/setup-java@v4
        with:
         java-version: '21'
         distribution: 'temurin'

      - name: Package with Maven
        run: mvn clean package


